sonar.projectKey=202602-GrupoH_tp-desarrollo
sonar.organization=202602-grupoh
sonar.host.url=https://sonarcloud.io

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.coverage.exclusions=**/config/**,**/dto/**,**/model/**,**/PlayersMarketApplication.java
