package com.cbo.players.exception;

public enum ErrorCode {
    CATALOG_SYNC_NOT_FOUND,
    CATALOG_SYNC_BUSY,
    PLAYER_STATISTICS_NOT_FOUND,
    WHOSCORED_ID_CONFLICT,
    USER_NOT_FOUND,
    INVALID_CREDENTIALS,
    EMAIL_ALREADY_EXISTS,
    USERNAME_ALREADY_EXISTS,
    USER_ALREADY_EXISTS,
    PLAYER_NOT_FOUND,
    API_KEY_NOT_FOUND,
    API_KEY_INACTIVE,
    UNAUTHORIZED_ACCESS,
    FORBIDDEN_OPERATION,
    VALIDATION_FAILED,
    INVALID_PARAMETER_FORMAT,
    MALFORMED_JSON,
    INTERNAL_SERVER_ERROR
}
